version: '3'

services:
  web:
    build: .
    working_dir: /app
    command: >
      bash -c "python manage.py migrate
      && python3 manage.py collectstatic --noinput
      && gunicorn pinry.wsgi:application -b 0.0.0.0:8000 --timeout 30"
    ports:
      - "127.0.0.1:2048:8000"
    environment:
      - SECRET_KEY=CHANGE-ME
    user: ${CURRENT_UID}
    volumes:
      - .:/app
    restart: always
